### ISSUE TITLE
Testing the Components

### ISSUE THREAD

**Issue by mikeshams** [gurman1995/capstone-project-embt-2020#1]
Gurman - What issues did you encounter during testing the components? How did you resolve the,?

**Comment by gurman1995** [comment]
During testing of hardware components i have faced 2 or 3 issues which i solved later.when i tried to connect wifi esp8266 with arduino IDE .I faced error because I didn’t select the right board in Arduino IDE for wifi esp8266.then I changed the board from arduino to esd8266. after this issue was solved.second issue that i faced was related to arduino chip test.while connecting arduino with arduino IDE I mistakenly used power cable instead of micro USB and while uploading that code on arduino chip it showed that serial port couldn’t solved then I searched about this problem online.i came to know that i need to use micro USB cable instead of power cable.Because function of power cable is just to give input voltage to chip
