### ISSUE TITLE
Gyroscope Interfacing

### ISSUE THREAD

**Issue by mikeshams** [gurman1995/capstone-project-embt-2020#3]
Soumya- 1) What issues did you gace when interfacing the gyroscope/ accelerometer? 2) How did you resolve them?

**Comment by Soumya977** [comment]
1. When gyroscope was interfaced with arduino UNO, I faced issues regarding connections. My problems in connection was that I didn’t give a common VCC or ground connection on the breadboard from both arduino and sensor Gnd,VCC. At that point, the serial monitor didn’t show any output, except establishing connection.
2. This issue was resolved when the VCC and Gnd connections from both sensor and arduino board was given a common ground and VCC on the breadboard. Then it worked perfectly. And connecting arduino with sensor and using arduino IDE is quite simple.

**Comment by Soumya977** [comment]
3. For the machine learning design and generation of the output, gestures were made using the sensor and the sensor recognizes particular gestures and compare with the data trained. Firstly, the sensor must be oriented in a comfortable position and gestures are to be made to train the data for each letter. Each letter must be trained at least ten times and usually more than that. Collecting the data must be accurate enough so that the overlapping with letters does not happen. When sensor was interfaced to perform the machine learning task, the orientation of the sensor was greatly affected since we work on a breadboard. Breadboard connections using connecting wires can cause fluctuations of the data training and thereby, the output data generated. After many researches regarding the machine learning designing, we came to know that the sensor orientation is the first and foremost factor that is affecting the data generation. Unlike any other data generation, machine learning data can only be produced, if the sensor is fixed properly. Also, while training the data the sensor must be in the fixed position and orientation and this must be carried throughout for the gesture output generation as well. 
4. We had trained each letter 10- 20 times. When this trained data did not generate a proper output, the main tasks was to erase all the data collected and start training for all the letters again. Each letter may resemble the other letters in some or the other way, therefore, collecting data is to be done very carefully as we can. This can limit overlapping with other letters.
5. another issue faced was The sensor got damaged when we soldered on pcb and trained it. so we ordered a new one, soldered and trained again
