### ISSUE TITLE
WIFI Module Interfacing

### ISSUE THREAD

**Issue by mikeshams** [gurman1995/capstone-project-embt-2020#4]
Gurman - 1) What issues did you face when interfacing the WiFi module to the BBB according to your email)? 2) How did you resolve them? 3) Modify your proposal! 4) Modify your code and demonstrate the strength of the WiFi signal result 5) Upload your code into the repository

**Comment by gurman1995** [comment]
While interfaced beaglebone black with wifi module esp8266. I faced some issues .while interfaced wifi module 8266 with wifi network i chosed 115200 baud frequency then it showed error and i didn't get desired output . to solved this error i searched online and i found that it could be done with 9600 baud frequency.2nd issue that i faced was related to connection .earlier i planned to go with GPIO pins but it didn’t work for me and showed COM4 not formed on the output while performed esp code on arduino IDE. So, because of that i selected USB protocol because it’s too easy to use and i got same output as that with GPIO pins. 3rd issue i faced when i compiled the esp code it showed serial print not formed on the output. then i searched online and download library for wifi module esp8266 and i got desired output
