### ISSUE TITLE
interfacing the LCD Display with the BBB

### ISSUE THREAD

**Issue by mikeshams** [gurman1995/capstone-project-embt-2020#6]
Soumya - 1) What issue did you have when interfacing the LCD Display with the BBB? 2)How did you resolve them? 3) Discuss if you are able to use 8-bit mode? 4) Discuss if you are able to change the font size?

**Comment by Soumya977** [comment]
1.) Issues faced when interfacing LCD display with BBB.
While interfacing the lcd display with beaglebone black, connection with the VCC of lcd is to be made with the VCC of BBB. BBB has four 5v pins which is two VDD_5V pins and two SYS_5V pins; that is P9_5, 6 (VCC 5V) or P9_7, 8(SYS 5V) pin on the BBB. 
The P9_5 or P9_6 VCC 5V pin will only be powered if a 5V adapter is plugged in to the barrel jack. Since I am connecting the BBB using USB cable this doesn't work. I got confused here with the VCC connection. 
2.) How did i resolve them
After browsing for the pinout details of BBB and checking the connection details of BBB, I realized that, if powering over USB we need to use the P9_7 or 8 (SYS 5V) pin instead.

3) Discuss if you are able to use 8-bit mode?
According to my research,16*2 LCD display can work in 8 bit mode. With the I2c interface board, LCD can work pretty stable in 8 bit mode, with dedicated control bits. Each character and command is sent to the LCD as a byte (8 bits) of data. So in 4 bit mode, the byte is split into two sets of 4 bits which are sent one after the other over 4 data wires.

4) Discuss if you are able to change the font size?
Character lcds can display character of font size 5×8 and 5×10. 
In 5xn, 5 represents number of coulombs and N represents number of rows. 
Some lcd’s can only display character in 5×8 font.
If you look closely at the LCD, you can see the small rectangles that form the individual characters of the LCD. 
The 16*2 LCD that we are using in our project can display only 5*8 font. Each rectangle is made up of a grid of 5×8 pixels.

![Screenshot (118)](https://user-images.githubusercontent.com/54857396/100449267-9d208280-3081-11eb-877c-bfc9cf375cee.png)

The Font size 'F' defined in the data bit DB2 of the LCD display instruction set is set to zero for 16*2 LCD, which is predefined. Thus, 5*8 font size can only be displayed by setting 'F' of DB2 zero. If the font size 'F' of DB2 is changed to one, it displays garbage values instead of character [values.]
