### ISSUE TITLE
interfacing the project to the cloud

### ISSUE THREAD

**Issue by mikeshams** [gurman1995/capstone-project-embt-2020#7]
Gurman - What issues did you face interfacing the project to the cloud? How did you resolve them?

**Comment by gurman1995** [comment]
While interfacing beaglebone black with adafruit(cloud).i faced some issues .while interfacing esp8266 with beaglebone black when i pressed any character from putty and that character uploaded on adafruit but with some garbage value.Then i searched about this issue and i came to know that i need to modify my code in arduino IDE and need to add adafruit library in that . Also i used one more while condition in the same code .later on i solved the issue.2nd issue i faced related to adafruit account.suddenly my code stopped working and nothing was uploaded on adafruit.it was because i uploaded so many character in a single time and it made unstability of code.later on i solved the issue.
